"""date columns to utc

Revision ID: 21ee688a6aa6
Revises: df4c786a55cc
Create Date: 2020-09-08 14:41:25.095573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ee688a6aa6'
down_revision = 'df4c786a55cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('blacklisted_on_utc', sa.DateTime(), nullable=False))
    op.drop_column('blacklist_tokens', 'blacklisted_on')
    op.add_column('users', sa.Column('registered_on_utc', sa.DateTime(), nullable=False))
    op.drop_column('users', 'registered_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_on', sa.DATETIME(), nullable=False))
    op.drop_column('users', 'registered_on_utc')
    op.add_column('blacklist_tokens', sa.Column('blacklisted_on', sa.DATETIME(), nullable=False))
    op.drop_column('blacklist_tokens', 'blacklisted_on_utc')
    # ### end Alembic commands ###
