"""tickets_and_events

Revision ID: df4c786a55cc
Revises: 38001af9be63
Create Date: 2020-09-08 13:53:47.350860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4c786a55cc'
down_revision = '38001af9be63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('initial_number_of_tickets', sa.Integer(), nullable=False),
    sa.Column('additional_number_of_tickets', sa.Integer(), nullable=True),
    sa.Column('guid', sa.BLOB(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('date_created_utc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('guid', sa.BLOB(), nullable=False),
    sa.Column('is_redeemed', sa.Boolean(), nullable=True),
    sa.Column('date_created_utc', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('event')
    # ### end Alembic commands ###
